### ISSUE TITLE
Document type of result after quasiquotation

### ISSUE THREAD

**Issue by 3noch** [tmhedberg/here#14]
Does the quasiquoter produce `String`, `IsString a`, or something else?

**Comment by tmhedberg** [comment]
It produces a string literal which is spliced into the AST at compile time, and follows all of the same rules as ordinary string literals in the source code. That is, without any language extensions, it has type `String`, and with `OverloadedStrings` enabled, it has type `IsString a => a`.

**Comment by 3noch** [comment]
@tmhedberg Oh wow. That...makes sense! Well in that case I have found my favorite QuasiQuoter!

**Comment by 3noch** [comment]
In that case, it might be useful to document that awesomeness for people like me who don't connect the dots?

**Comment by tmhedberg** [comment]
Sure, that makes sense. I added a note to the README mentioning this.
