### ISSUE TITLE
internal blank lines always stripped ?

### ISSUE THREAD

**Issue by simonmichael** [tmhedberg/here#20]
I am seeing all blank lines being stripped, by `here` and `hereLit`. So eg paragraphs of text separated by blank lines are run together in the output. Is this expected ?

**Comment by tmhedberg** [comment]
No, it's not expected, nor can I reproduce it. Please provide a minimal
example that demonstrates the problem.

**Comment by simonmichael** [comment]
Ok thank you, I will dig deeper and report back.

**Comment by simonmichael** [comment]
Sorry, it was https://github.com/ndmitchell/cmdargs/issues/49.
