### ISSUE TITLE
Expose parsers?

### ISSUE THREAD

**Issue by 3noch** [tmhedberg/here#25]
I would like to use your library for interpolating in other contexts. A large majority of your code could be reused. Would you be open to accepting a PR that exposed your parsers with some additional abstraction or a PR that used an upstream library (derived from your parsers) to do the parsing?

**Comment by tmhedberg** [comment]
I guess it depends on what you mean, exactly. Exposing previously-internal implementation details as part of the library's API implies committing to keeping those details relatively stable in the future. It's not as if this library is seeing active development these days, though, so maybe that doesn't matter much.

What other contexts do you have in mind for using the parsers? I'm curious if it's a case that `here` could reasonably be extended to cover, or if it's out of scope for this library.

Of course, you could always just copy the code and reuse it however you like without depending on `here` directly.

**Comment by 3noch** [comment]
I copied your code almost verbatim here: https://github.com/3noch/postgresql-simple-interpolate/blob/63d6ff95ce13246e0d7c33e60e21842ac74ec50d/src/Database/PostgreSQL/Simple/SqlQQ/Interpolated/Parser.hs

**Comment by 3noch** [comment]
I'd be happy to more "officially" recognize your authorship by depending on your code directly though.

**Comment by 3noch** [comment]
Also, tangentially, I've been told that `haskell-src-meta`'s parsers can actually give you semantically different Haskell than the same expression directly processed by GHC. Have you ever run into something like this? The `haskell-src-meta` parsers are apparently unaware of operator fixity outside of Prelude and cannot use the extensions used by a calling module. I have not spent much time validating these claims but anything that changes semantics does seem dire.

**Comment by tmhedberg** [comment]
Copying the code is fine with me if it's fine with you. :)

I haven't run into the issues you mention with `haskell-src-meta`, but that doesn't mean they don't exist. I myself am not a very heavy user of this library these days, but if you run into any weird problems that might be related to this, definitely file another bug.

**Comment by 3noch** [comment]
Haha ok. I'll keep an eye out for issues with `haskell-src-meta` but I also haven't actually run into any issues, and I've even *tried*.
